name: learn-github-actions
run-name: ${{ github.actor }} is ${{ github.event.repository.updated_at}}
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: sleep 2
