name: learn-github-actions
run-name: ${{ github.actor }} is "echo $(date +'%Y-%m-%dT%H:%M:%S')"
on:
  workflow_dispatch:
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: sleep 20
